### ISSUE TITLE
Add a License to Project

### ISSUE THREAD

**Issue by CarlosMillanSfC** [CarlosMillanSfC/github-projects-playground#3]
Hey @TomasTubertSFC . I wonder what type of license I should add to this project.

**Comment by TomasTubertSFC** [comment]
Pues la MIT. No saber eso...

**Comment by CarlosMillanSfC** [comment]
Thanks Tomás, you're the worst. I added the LICENSE file.

**Comment by TomasTubertSFC** [comment]
Well done @CarlosMillanSfC
